package com.iti.weatherwatch.favorites.view

import android.content.Context
import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.core.os.bundleOf
import androidx.navigation.Navigation
import androidx.recyclerview.widget.RecyclerView
import com.iti.weatherwatch.R
import com.iti.weatherwatch.databinding.FavoriteCardBinding
import com.iti.weatherwatch.datasource.model.OpenWeatherApi
import com.iti.weatherwatch.favorites.viewmodel.FavoritesViewModel
import com.iti.weatherwatch.util.getCityText
import com.iti.weatherwatch.util.getSharedPreferences

/*
This is an implementation of a RecyclerView Adapter in Kotlin for a Favorites screen in a weather app.

The class FavoriteAdapter takes two parameters in its constructor: a Context and a FavoritesViewModel. It has a list of OpenWeatherApi objects named favoriteList which will be used to populate the RecyclerView.

The class has an inner class named ViewHolder which extends RecyclerView.ViewHolder. This ViewHolder class contains a binding object FavoriteCardBinding which is auto-generated by the view binding system in Android. This binding object contains all the views of a single item in the RecyclerView.

The onCreateViewHolder() method is responsible for inflating the layout of a single item in the RecyclerView and returning a ViewHolder object.

The onBindViewHolder() method is responsible for setting the data of each item in the RecyclerView. It gets the OpenWeatherApi object at the current position from the favoriteList and binds it to the corresponding views in the ViewHolder. It also sets up click listeners for the delete button and the whole card view.

The getItemCount() method returns the number of items in the favoriteList.

Overall, this adapter is used to display a list of favorite cities in the app, and each item in the list displays the city name, a delete button, and an onClick listener that navigates to a new screen displaying the weather details of the selected city.
 */
class FavoriteAdapter(private val context: Context, private val viewModel: FavoritesViewModel) :
    RecyclerView.Adapter<FavoriteAdapter.ViewHolder>() {
    var favoriteList: List<OpenWeatherApi> = emptyList()

    class ViewHolder(val binding: FavoriteCardBinding) :
        RecyclerView.ViewHolder(binding.root)

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        return ViewHolder(
            FavoriteCardBinding.inflate(
                LayoutInflater.from(parent.context),
                parent,
                false
            )
        )
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        val favorite = favoriteList[position]
        val language = getSharedPreferences(context).getString(
            context.getString(R.string.languageSetting),
            "en"
        )!!
        holder.binding.textFavoriteCountry.text =
            getCityText(context, favorite.lat, favorite.lon, language)
        holder.binding.btnDelete.setOnClickListener {
            viewModel.deleteFavoriteWeather(favorite.id)
        }
        holder.binding.favoriteCardView.setOnClickListener {
            val bundle = bundleOf("id" to favorite.id, "lat" to favorite.lat, "lon" to favorite.lon)
            Navigation.findNavController(it)
                .navigate(R.id.action_navigation_dashboard_to_displayFavoriteWeather, bundle)
        }
    }

    override fun getItemCount(): Int {
        return favoriteList.size
    }
}
